first_app/config/routes.rb
FirstApp::Application.routes.draw do

  get "pages/home"

  get "pages/contact"

  resources :microposts

  resources :users
  match '/sign in',  :to => 'users#new'
  match '/signup',  :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  root :to => 'pages#home'

end

first_app/app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
	belongs_to :user
	validates :content, :length => { :maximum => 140 }
	
end

first_app/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

   validates :name,  :presence => true,
                    :length   => { :maximum => 50 }
   validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  # validates :password, :presence     => true,
                     #  :confirmation => true,
                      # :length       => { :within => 6..40 }
 #before_save :encrypt_password
 #def has_password?(submitted_password)
  #  encrypted_password == encrypt(submitted_password)
  #end
# def self.authenticate(email, submitted_password)
 #   user = find_by_email(email)
  #  return nil  if user.nil?
   # return user if user.has_password?(submitted_password)
  #end
 #private

  #  def encrypt_password
   #   self.salt = make_salt if new_record?
    #  self.encrypted_password = encrypt(password)
   # end

    #def encrypt(string)
     # secure_hash("#{salt}--#{string}")
    #end

   # def make_salt
     # secure_hash("#{Time.now.utc}--#{password}")
    #end

    #def secure_hash(string)
     # Digest::SHA2.hexdigest(string)
    #end
end

first_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

first_app/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(params[:micropost])

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render json: @micropost, status: :created, location: @micropost }
      else
        format.html { render action: "new" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.json
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end
end

first_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
	@title="Home"
  end

  def contact
	@title="Contact"
  end
def about
    @title = "About"
  end
end

first_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
   def show
   @user = User.find(params[:id])
    @title = @user.name
  end

  def new
    @title = "Sign up"
	@user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end
def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

first_app/app/helpers/application_helper.rb
module ApplicationHelper
def title
    base_title = "Ruby on Rails Tutorial Sample App"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

first_app/app/helpers/microposts_helper.rb
module MicropostsHelper
end

first_app/app/helpers/pages_helper.rb
module PagesHelper
end

first_app/app/helpers/users_helper.rb
module UsersHelper
end

first_app/app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
	<li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

first_app/app/views/layouts/_header.html.erb
<header>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to 'Sign in', new_user_path %></li>
    </ul>
  </nav>
</header>

first_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
 	<%= stylesheet_link_tag    "application", :media => "all" %>
 	<%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
  
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

first_app/app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

first_app/app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

first_app/app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.user_id %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>
<%= link_to 'Main page', :controller => "pages", :action => :home %>

first_app/app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'All microposts', microposts_path %>
<%= link_to 'Main page', :controller => "pages", :action => :home %>

first_app/app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micropost.content %>
</p>

<p>
  <b>User:</b>
  <%= @micropost.user_id %>
</p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

first_app/app/views/pages/about.html.erb
    <h1>About Us</h1>
    <p>
      Story death. 4t class/ MIREA
    </p>

first_app/app/views/pages/contact.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails Sample App | <%= @title %></title>
  </head>
  <body>
    <h1>Contact</h1>
    <p>
      by Story Death
    </p>
  </body>
</html>

first_app/app/views/pages/home.html.erb
		<h1>HELLO, RAILS</h1>
		<h2> This is my first try! </h2>
		<p>Find file with this words in app/views/pages/home.html.erb</p>
<%= link_to 'New post', :controller => "microposts", :action => :new %>
<%= link_to 'New user', :controller => "users", :action => :new %>
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>