sampl_app/config/routes.rb
SamplApp::Application.routes.draw do
  get "sessions/new"

  
  resources :users
  resources :SchedulesController
  resources :sessions, :only => [:new, :create, :destroy]
	resources :microposts, :only => [:create, :destroy]
  match '/signup',  :to => 'users#new'
  match '/signup', :to => 'user#show'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  get "pages/home"
  get "pages/contact"

  get "pages/about"
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',   :to => 'pages#help'
  root :to => 'pages#home'

  match ':controller(/:action(/:id))(.:format)'
end

sampl_app/app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <%= link_to "О кабинете", about_path %>
      <%= link_to "Контакты", contact_path %>
      
    </ul>
  </nav>
</footer>

sampl_app/app/views/layouts/_header.html.erb
<header>
  <nav class="round">
    <ul>
       <li><%= link_to "Домашняя страница", root_path %></li>
      <% if signed_in? %>
     <li><%= link_to "Пользователи", users_path %></li>
	<% if current_user.admin? %>
	<li><%= link_to "Расписание", :controller => "schedules", :action => :create %></li>
	<%end%>
      <li><%= link_to "Профиль", current_user %></li>
      <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Помощь", help_path %></li>
	
      <% if signed_in? %>
      <li><%= link_to "Выйти", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Войти", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

sampl_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag 'style.css', :media => 'screen' %>
  <%= csrf_meta_tags %>
</head>
 <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
	<% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>